name: Weather Data Workflow (Hourly)

on:
  schedule:
    - cron: '0 * * * *'  # This runs the workflow at the start of every hour
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-dotnet@v4 #-python@v3
      # with:
      #   python-version: '3.8'  
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run the python script
      run: python weather_data.py
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update data" -a || echo "No changes to commit"
        git push https://${{ secrets.DAM_TOKEN }}@github.com/marksm88/weather-data.git
